### ISSUE TITLE
Maximum context length

### ISSUE THREAD

**Issue by ovpn-dev** [rahul2002m/ChatPDF#6]
BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 4097 tokens. However, your messages resulted in 6988 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}.

How can i fix this? Any pointers please

**Comment by rahul2002m** [comment]
Hi @ovpn-dev,
To solve this issue, you can use the GPT-Turbo 16K model, which supports up to 16,000 tokens. If you need more, consider using GPT-4o, which supports up to 128,000 tokens.
